<!-- Static navbar -->
<div class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><img src="images/logo.png" style="height:100%;"></a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="#/">Home</a></li>
        <li class="dropdown">
        <a href="" class="dropdown-toggle" data-toggle="dropdown">Customers <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#/customer-list">Customer List</a></li>
            <li><a href="#/customer-creation">Create a Customer</a></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</div>
